site_name: MIDB Neuroimaging Hub readthedocs

theme: 
    name: readthedocs
    collapse_navigation: True
    logo: brain-illustrations1.png
    
plugins:
    - search

#theme:     
#    collapse_navigation: True
#    icon:
#    admonition:
#      <type>: <icon> 

docs_dir: docs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav: 
    - Welcome: index.md

    - MSI 101: #msi
        - Getting access: msi/msi.md
        - Transferring data on MSI: msi/transfer.md
        - For PIs - Activate and maintain your share: msi/maintenance.md
        - For PIs - Make changes to your share: msi/changes.md      
        
    - CMRR: #cmrr
        - Step 1 - Registration and Access: cmrr/user.md
        - Step 2 - Human Research Training: cmrr/operator.md
        - CMRR Servers (accessing your data): cmrr/naxos.md
        - Transfering data from CMRR: cmrr/transfer2.md
        - Help! Where is my data?: cmrr/search.md
    
    - MIDB: #midb
        - MIDB Imaging Suite: midb/midbaccess.md
        - CNBD Access: midb/cnbd.md
        - At The Console: midb/console.md
        - Safety at MIDB: midb/safety.md
        - FAQs: midb/faqs.md

    #- Data Storage Options:

    - Data Handling on MSI: #usingmsi
        - Troubleshooting: usingmsi/troubleshooting.md 
        - usingmsi/location.md 

    - Shortcuts: shortcuts.md